# Generated by Django 5.0.1 on 2025-02-18 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Almazdiamondmo_app', '0003_remove_products_video_products_videos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='images',
        ),
        migrations.RemoveField(
            model_name='products',
            name='videos',
        ),
        migrations.CreateModel(
            name='ProductFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_images/')),
                ('video', models.FileField(blank=True, null=True, upload_to='product_video/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Almazdiamondmo_app.products')),
            ],
        ),
    ]
