# Generated by Django 5.0.1 on 2025-02-18 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Almazdiamondmo_app', '0005_remove_productfiles_image_remove_productfiles_video_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='product_main_image/'),
        ),
    ]
