# Generated by Django 5.0.1 on 2025-02-18 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Almazdiamondmo_app', '0006_products_main_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='product_main_image/'),
        ),
    ]
