# Generated by Django 5.0.1 on 2025-02-22 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Almazdiamondmo_app', '0008_ringsettings_stone_ringdetails_stonedetails_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stone',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
