# Generated by Django 5.0.1 on 2025-02-22 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Almazdiamondmo_app', '0011_combination_combinationfiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stone',
            name='stone_clarity',
            field=models.CharField(blank=True, choices=[('SH', 'SH'), ('VS2', 'VS@'), ('VS1', 'VS1'), ('VVS2', 'VVS2'), ('VVS1', 'VVS1'), ('IF', 'IF'), ('FL', 'FL')], max_length=100, null=True),
        ),
    ]
