# Generated by Django 5.0.1 on 2025-03-01 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Almazdiamondmo_app', '0013_ringsettingtypes_remove_ringdetails_ring_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ring_setting_varients',
            new_name='Ring_setting_variants',
        ),
    ]
