# Generated by Django 5.0.1 on 2025-03-01 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Almazdiamondmo_app', '0014_rename_ring_setting_varients_ring_setting_variants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ringsettings',
            name='currency',
        ),
    ]
