# Generated by Django 5.0.1 on 2025-03-02 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Almazdiamondmo_app', '0015_remove_ringsettings_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='combination',
            name='ring',
        ),
        migrations.AddField(
            model_name='combination',
            name='ring_variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Almazdiamondmo_app.ring_setting_variants'),
        ),
        migrations.AlterField(
            model_name='stone',
            name='stone_clarity',
            field=models.CharField(blank=True, choices=[('SH', 'SH'), ('VS2', 'VS1'), ('VS1', 'VS1'), ('VVS2', 'VVS2'), ('VVS1', 'VVS1'), ('IF', 'IF'), ('FL', 'FL')], max_length=100, null=True),
        ),
    ]
