# Generated by Django 5.0.1 on 2025-03-08 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Almazdiamondmo_app', '0016_remove_combination_ring_combination_ring_variant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ring_setting_variants',
            name='carat',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='ring_setting_variants',
            name='profile',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='ring_setting_variants',
            name='width',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='ringdetails',
            name='ring_images_360',
            field=models.ImageField(blank=True, null=True, upload_to='260_ring_image/'),
        ),
        migrations.AddField(
            model_name='stonedetails',
            name='stone_images_360',
            field=models.ImageField(blank=True, null=True, upload_to='260_stone_image/'),
        ),
    ]
