# Generated by Django 5.0.1 on 2025-03-08 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Almazdiamondmo_app', '0017_ring_setting_variants_carat_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ring_variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Almazdiamondmo_app.ring_setting_variants')),
                ('stone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Almazdiamondmo_app.stone')),
            ],
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ring_variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Almazdiamondmo_app.ring_setting_variants')),
                ('stone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Almazdiamondmo_app.stone')),
            ],
        ),
    ]
