# Generated by Django 5.0.1 on 2025-03-08 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Almazdiamondmo_app', '0018_cart_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='stone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Almazdiamondmo_app.stone'),
        ),
    ]
