# Generated by Django 5.0.1 on 2025-03-08 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Almazdiamondmo_app', '0020_alter_cart_stone'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='item_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
